### ISSUE TITLE
Audio mixing and volume issues

### ISSUE THREAD

**Issue by aglasgall** [TeamApexQ/apexq#3]
I haven't quantified it yet (and will gather more data in a bit), but there's something odd about the volume scale, at least for notification. I have it down to one notch above vibrate and it's still shockingly loud.

**Comment by nardholio** [comment]
Volume scale is an adjustable overlay, the default is 20 steps of 5% each. Absolute volume is a problem though, and we need to convince someone to tone it down a bit.

**Comment by infernix** [comment]
In /etc/snd_soc_msm/snd_soc_msm_2x line 2785 at:

SectionDevice  
        Name "Speaker"
        Comment "Speaker Rx device"

EnableSequence    

'RX5 Digital Volume':1: should not exceed 67.7% while LINEOUTx are at 100 as to not create audio clipping. I think if this is raised too high, then the lowest step in the volume scale is still too high, because the volume adjustment in Android itself is internal and not the actual Alsa volume control.

**Comment by kornyone** [comment]
Just throwing this out there.  There was a serious issue with a2dp overpowering the stereo in my 2012 Kia Optima (Infinity sound system).  I found the following two patches for bluedroid in CM gerrit and compiled them in:

http://review.cyanogenmod.org/#/c/33341/  not yet merged
http://review.cyanogenmod.org/#/c/33227/3   very recently merged

For me, a2dp now sounds great.  It also helps on my Bluetooth a2dp Monster speaker.  

Other users report that a2dp volume is too low, rather than too loud.  These patches may help them too.

**Comment by nardholio** [comment]
Here is a link to infernix's patch http://bpaste.net/show/WdnXwZ1f2WtbFYkmABAk/ 
need to discuss it with lbcoder
Also want to discuss https://github.com/CyanogenMod/android_device_samsung_d2-common/commit/9263d9d71fa44f600c534970a37b5e4ff06af016

**Comment by infernix** [comment]
I've tested the BT SCO voicedial, it is currently broken so https://github.com/CyanogenMod/android_device_samsung_d2-common/commit/9263d9d71fa44f600c534970a37b5e4ff06af016 should be applied and then retested.

**Comment by infernix** [comment]
There's a real problem with the audio when you try to use Skype on a headset or over bluetooth. There's a ton of background noise and the mic input is very low.

It's going to require some real digging to figure out the mixer setup, will work on it some.

**Comment by infernix** [comment]
https://github.com/TeamApexQ/apexq/wiki/Mixing

**Comment by infernix** [comment]
Source code for korean galaxy r 4.1.2 has a samsung vendor libalsa-intf: http://paste.ubuntu.com/5612636/

need to grab those blobs and try those + this libalsa-intf, then test that build

**Comment by infernix** [comment]
The galaxy r blobs and libalsa-intf might also need https://bitbucket.org/cyanogenmod/android_frameworks_av/commits/87dc005928a231a6809a588ae84ed98e0313b170

**Comment by infernix** [comment]
With the latest nightlies, all audio works, all levels are fine, and A2DP is working too.
